import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { SharedService } from './shared.service';
import { AuthService } from './auth.service';

@Injectable({
  providedIn: 'root'
})
export class TruequeService {

	constructor(private http: HttpClient,
		private authService: AuthService,
		private sharedService:SharedService
		) { }

	getTrueque(): Observable<any> {

		var token = localStorage.getItem('token');

		const headers = new HttpHeaders({
			"Authorization": "Bearer "+token,
			"Content-Type": "application/x-www-form-urlencoded"
		});

		return this.http.get(`http://fenicia.meteoracolombia.co:8010/4p1/GrupoElementosController.php`,{headers}).pipe(
			catchError(this.sharedService.handleErrorResponse)
		);
	}

  getNextId(): Observable<any> {

    var token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJJcjdQT1NuQmw0b3Z5WWNZQjNzUzZHVXFoSG5TWjdpR2xiVlB3YkM1VnYwIn0.eyJleHAiOjE3MDY4MDM0MDAsImlhdCI6MTcwNjgwMjUwMCwianRpIjoiYTM5NjQ2MzktYzU4YS00NGFkLWFjYWItY2QyNGY4MmIxNTRmIiwiaXNzIjoiaHR0cDovL2ZlbmljaWEubWV0ZW9yYWNvbG9tYmlhLmNvOjgwODAvcmVhbG1zL21ldGVvcmEiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImFjY291bnQiXSwic3ViIjoiN2ZlY2I3NmItMTk4Yy00Zjc1LTgwMDMtYWFjMzRkYWFmYTUwIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibWV0ZW9yYV93cyIsInNlc3Npb25fc3RhdGUiOiI2OGU1MmVjYS0wMTJmLTQ2NDctYjRiMy00NzBjZTk4NmQ5Y2IiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1tZXRlb3JhIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJyZWFsbS1tYW5hZ2VtZW50Ijp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwicmVhbG0tYWRtaW4iLCJjcmVhdGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6IjY4ZTUyZWNhLTAxMmYtNDY0Ny1iNGIzLTQ3MGNlOTg2ZDljYiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoid3NtM3QzMHI0LiEyMDIzIiwiZ2l2ZW5fbmFtZSI6IiIsImZhbWlseV9uYW1lIjoiIn0.BcuZ1yAUvCIzrm8JWOEUY5ObCZaUQSqWDfYqIvYk6XNsmEpyGQsVkRxDKh3wmvq12pI099aydvgi2I4Yw0WNmiRvm6OWcKvBYY5t5CFZMghvVakMrIrqvN-hCmZ1DUPSN59JH5vHq0CqydAsnGN6X7XEDNtNkj61P931u79CDl7aielyQyFM8Six9qPf9p-zFNWQXdKc7xZxyg78VkqyrOx2xuuEX8VqLxyUzPeCw3Kh2SsroT7aUuM8nUKMy-EpRHcVqmuBbmAqQ7uQOoixZs6xXR7v0mUGH6zorIdmp2kMx7pkcokM7TuksEGXiOTQzCR2YX7GbQGRepf43ORvEA";

		const headers = new HttpHeaders({
			"Authorization": "Bearer "+token,
			"Content-Type": "application/x-www-form-urlencoded"
		});

		return this.http.get(`http://fenicia.meteoracolombia.co:8010/4p1/ProxPTController.php`,{headers}).pipe(
			catchError(this.sharedService.handleErrorResponse)
		);
	}

  getPar(): Observable<any> {

    var token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJJcjdQT1NuQmw0b3Z5WWNZQjNzUzZHVXFoSG5TWjdpR2xiVlB3YkM1VnYwIn0.eyJleHAiOjE3MDY4MDM0MDAsImlhdCI6MTcwNjgwMjUwMCwianRpIjoiYTM5NjQ2MzktYzU4YS00NGFkLWFjYWItY2QyNGY4MmIxNTRmIiwiaXNzIjoiaHR0cDovL2ZlbmljaWEubWV0ZW9yYWNvbG9tYmlhLmNvOjgwODAvcmVhbG1zL21ldGVvcmEiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImFjY291bnQiXSwic3ViIjoiN2ZlY2I3NmItMTk4Yy00Zjc1LTgwMDMtYWFjMzRkYWFmYTUwIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibWV0ZW9yYV93cyIsInNlc3Npb25fc3RhdGUiOiI2OGU1MmVjYS0wMTJmLTQ2NDctYjRiMy00NzBjZTk4NmQ5Y2IiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1tZXRlb3JhIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJyZWFsbS1tYW5hZ2VtZW50Ijp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwicmVhbG0tYWRtaW4iLCJjcmVhdGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6IjY4ZTUyZWNhLTAxMmYtNDY0Ny1iNGIzLTQ3MGNlOTg2ZDljYiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoid3NtM3QzMHI0LiEyMDIzIiwiZ2l2ZW5fbmFtZSI6IiIsImZhbWlseV9uYW1lIjoiIn0.BcuZ1yAUvCIzrm8JWOEUY5ObCZaUQSqWDfYqIvYk6XNsmEpyGQsVkRxDKh3wmvq12pI099aydvgi2I4Yw0WNmiRvm6OWcKvBYY5t5CFZMghvVakMrIrqvN-hCmZ1DUPSN59JH5vHq0CqydAsnGN6X7XEDNtNkj61P931u79CDl7aielyQyFM8Six9qPf9p-zFNWQXdKc7xZxyg78VkqyrOx2xuuEX8VqLxyUzPeCw3Kh2SsroT7aUuM8nUKMy-EpRHcVqmuBbmAqQ7uQOoixZs6xXR7v0mUGH6zorIdmp2kMx7pkcokM7TuksEGXiOTQzCR2YX7GbQGRepf43ORvEA";

		const headers = new HttpHeaders({
			"Authorization": "Bearer "+token,
			"Content-Type": "application/x-www-form-urlencoded"
		});

		return this.http.get(`http://fenicia.meteoracolombia.co:8010/4p1/ParFeniciaController.php`,{headers}).pipe(
			catchError(this.sharedService.handleErrorResponse)
		);
	}

  createProduct(data:any): Observable<any> {
    var token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJJcjdQT1NuQmw0b3Z5WWNZQjNzUzZHVXFoSG5TWjdpR2xiVlB3YkM1VnYwIn0.eyJleHAiOjE3MDY4MDM0MDAsImlhdCI6MTcwNjgwMjUwMCwianRpIjoiYTM5NjQ2MzktYzU4YS00NGFkLWFjYWItY2QyNGY4MmIxNTRmIiwiaXNzIjoiaHR0cDovL2ZlbmljaWEubWV0ZW9yYWNvbG9tYmlhLmNvOjgwODAvcmVhbG1zL21ldGVvcmEiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImFjY291bnQiXSwic3ViIjoiN2ZlY2I3NmItMTk4Yy00Zjc1LTgwMDMtYWFjMzRkYWFmYTUwIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibWV0ZW9yYV93cyIsInNlc3Npb25fc3RhdGUiOiI2OGU1MmVjYS0wMTJmLTQ2NDctYjRiMy00NzBjZTk4NmQ5Y2IiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1tZXRlb3JhIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJyZWFsbS1tYW5hZ2VtZW50Ijp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwicmVhbG0tYWRtaW4iLCJjcmVhdGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6IjY4ZTUyZWNhLTAxMmYtNDY0Ny1iNGIzLTQ3MGNlOTg2ZDljYiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoid3NtM3QzMHI0LiEyMDIzIiwiZ2l2ZW5fbmFtZSI6IiIsImZhbWlseV9uYW1lIjoiIn0.BcuZ1yAUvCIzrm8JWOEUY5ObCZaUQSqWDfYqIvYk6XNsmEpyGQsVkRxDKh3wmvq12pI099aydvgi2I4Yw0WNmiRvm6OWcKvBYY5t5CFZMghvVakMrIrqvN-hCmZ1DUPSN59JH5vHq0CqydAsnGN6X7XEDNtNkj61P931u79CDl7aielyQyFM8Six9qPf9p-zFNWQXdKc7xZxyg78VkqyrOx2xuuEX8VqLxyUzPeCw3Kh2SsroT7aUuM8nUKMy-EpRHcVqmuBbmAqQ7uQOoixZs6xXR7v0mUGH6zorIdmp2kMx7pkcokM7TuksEGXiOTQzCR2YX7GbQGRepf43ORvEA";

		const headers = new HttpHeaders({
			"Authorization": "Bearer "+token,
			"Content-Type": "application/x-www-form-urlencoded"
		});

		return this.http.post(`http://fenicia.meteoracolombia.co:8010/4p1/ProductController.php`,data, {headers}).pipe(
			catchError(this.sharedService.handleErrorResponse)
		);
	}
}
